service: employee-bank-details-get-service
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.employeeBankDetails}
custom:
  employeeBankDetails: employee-bank-details-table-${self:provider.stage}
plugins:
  - serverless-iam-roles-per-function
functions:
  getEmployeeBankDetails:
    handler: api.getEmployeeBankDetails
    name: employee-bank-get
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: employeebank/{empId}
          method: GET
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:GetItem"
        Resource: !GetAtt PostsTable.Arn
  getAllEmployeeBankDetails:
    handler: api.getAllEmployeeBankDetails
    name: get-all-employee-bank-details
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: posts
          method: GET
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:Scan"
        Resource: !GetAtt PostsTable.Arn
resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.employeeBankDetails}
        AttributeDefinitions:
          - AttributeName: empId
            AttributeType: S
        KeySchema:
          - AttributeName: empId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1



