service: employee-bank-details-get-service
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1
  environment:
    DYNAMODB_TABLE_NAME: employeeBankDetails
  custom:
    employeeBankDetails: employee-bank-details-table-${self:provider.stage}
plugins:
  - serverless-iam-roles-per-function
functions:
  getBankDetails:
    handler: api.getBankDetails
    name: bank-get
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: employeebank/{empId}
          method: GET
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:GetItem"
        Resource: !GetAtt PostsTable.Arn
  getAllBanks:
    handler: api.getAllBanks
    name: get-all-bank
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: allEmployeeBankDetails
          method: GET
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:Scan"
        Resource: !GetAtt PostsTable.Arn
resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: employee-bank-details-table-dev
        AttributeDefinitions:
          - AttributeName: empId
            AttributeType: S
        KeySchema:
          - AttributeName: empId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
